server:
  port: 8181
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: 112788
  jpa:
    # 显示sql
    show-sql: true
    open-in-view: false
    hibernate:
      # 自动生成表结构
      ddl-auto: update
    properties:
      hibernate:
        # 格式化sql
        format_sql: true