server:
  port: 8181
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: 112788
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # druid 数据源专有配置
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      # 配置监控统计拦截的filters，stat：监控统计，wall：防御sql注入，log4j2：日志记录
      filters: stat,wall
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
  jpa:
    # 显示sql
    show-sql: true
    hibernate:
      # 自动生成表结构
      ddl-auto: update
    properties:
      hibernate:
        # 格式化sql
        format_sql: true